import numpy as np

a=np.arange(14,2,-1).reshape(3,4)
#最小值的位置
print(np.argmin(a))
#最大值的位置
print(np.argmax(a))
#平均值
print(np.mean(a))
print(a.mean())
print(np.average(a))
#中位数
print(np.median(a))
print(a)
#累加
print(np.cumsum(a))
#相差
print(np.diff(a))
#找出不是零的数
print(np.nonzero(a))
#排序
print(np.sort(a))
#转置(行列交换)
print(np.transpose(a))
#大于9改为9小于5改为5
print(np.clip(a,5,9))
#列的平均值
print(np.mean(a,axis=0))
#行的平均值
print(np.mean(a,axis=1))
